name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build
        run: cargo build --release

      - name: Zip Output
        run: |
          mkdir -p output
          cp target/release/train output/
          cp target/release/predict output/
          zip -r release_artifacts.zip output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nlp-release
          path: release_artifacts.zip
